import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/contexts/AuthProvider";
import QuizProvider from "@/contexts/QuizProvider";



export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-100 w-full">
        <AuthProvider>
          <QuizProvider>{children}</QuizProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
